---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update OS
      apt:
       name: "*"
       state: latest
       update_cache: yes
    - name: good stuff to have
      apt:
       name:
         - curl
       state: present

    - name: install nodesource
      command: "curl -fsSL https://deb.nodesource.com/setup_17.x | sudo -E bash -"
    
    - name: install my stuff
      apt:
        name: 
          - snapd
          - ansible
          - openjdk-8-jdk
          - nodejs
          - build-essential
        state: present
    
    - name: install idea
      snap:
        name:
          - intellij-idea-community
          - pycharm-community
        classic: yes
        state: present
    - name: install oh-my-bash
      command: '"sh -c "$(curl -fsSL https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh)'
  roles:
    - docker

  
    

      
