---
- hosts: localhost
  become: true
  pre_tasks:
    - name: update OS
      apt:
       name: "*"
       state: latest
       update_cache: yes
    - name: good stuff to have
      apt:
       name:
         - curl
       state: present

    - name: install nodesource gpg
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      
    - name: "Add nodejs 13.x ppa for apt repo"
      apt_repository:
        repo: deb https://deb.nodesource.com/node_17.x bionic main
        update_cache: yes
    
    - name: "Install nodejs"
      apt:
        update_cache: yes
        name: nodejs
        state: present
    
    - name: install my stuff
      apt:
        name: 
          - snapd
          - ansible
          - openjdk-8-jdk
          - nodejs
          - build-essential
        state: present
    
    - name: install idea
      snap:
        name:
          - intellij-idea-community
          - pycharm-community
        classic: yes
        state: present
    - name: install oh-my-bash
      command: '"/usr/bin/sh -c "$(/usr/bin/curl -fsSL https://raw.github.com/ohmybash/oh-my-bash/master/tools/install.sh)'
  roles:
    - docker

  
    

      
